version: '3'
services:
  database:
    image: postgres:12
    container_name: database
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  cache:
    image: redis:5-alpine
    container_name: cache
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - cache:/data

  app:
    container_name: app
    build: .
    environment:
      POSTGRES_URL: ${DOCKER_POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_HOST: ${DOCKER_REDIS_HOST}
      NODE_ENV: prod
    depends_on:
      - database
      - cache
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}

  migration:
    container_name: migration
    build: .
    environment:
      POSTGRES_URL: ${DOCKER_POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      REDIS_HOST: ${DOCKER_REDIS_HOST}
    command: sh -c "npm run migrate:deploy"
    links:
      - database
    depends_on:
      - database
    stop_grace_period: 3s

volumes:
  database:
  cache:
