version: '3'
services:
  db:
    image: 'postgres:14.2-alpine'
    container_name: 'db'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5433:5432'

  cache:
    image: 'redis:5-alpine'
    container_name: 'cache'
    ports:
      - '6379:6379'
    volumes:
      - 'cache:/data'

  api:
    container_name: 'api'
    build: .
    environment:
      DATABASE_URL: '${DATABASE_URL_DOCKER_URL}'
      NODE_ENV: prod
    depends_on:
      - 'db'
      - 'cache'
    restart: 'always'
    ports:
      - '8000:8000'

volumes:
  db: {}
  cache: {}
